### ISSUE TITLE
Missing database

### ISSUE THREAD

**Issue by jim-parry** [Alberts-Revenge/Project#17]
I have downloaded this, but cannot find any database SQL.
Your email suggested the application/database folder, which is not there.
There isn't a database folder inside assets either.
I see from your config that the database name is to be "projectdb", but cannot go any further without the database dump.

**Comment by sstan4411** [comment]
Wow I completely forgot to push and merge after I added the database.
Sorry, I don't know how I missed that...
I have done so now, perhaps too late :/

**Comment by jim-parry** [comment]
I took a look, and raised some issues.
It is looking much better, but not complete and a bit buggy.
See the issue comments!

**Comment by sstan4411** [comment]
Thanks a lot Jim, we'll try to fix as much as we can until we have to
submit. Enjoy your Spring break!
